[build]
  command = "npm run build && cp -r .next/standalone/. .next/deploy && cp -r .next/static .next/deploy/_next/static && cp -r public .next/deploy/public"
  publish = ".next/deploy"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["googleapis", "resend", "stripe"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
